### ISSUE TITLE
How to get the road network distance in PeMS ?

### ISSUE THREAD

**Issue by Daishijun** [nnzhan/Graph-WaveNet#12]
Hi , Thanks for sharing the code. Could you please tell me how to get the road network distance in PeMS ? I'm confused for a week.

**Comment by JarvisKevin** [comment]
Maybe you can refer the [DCRNN](https://github.com/liyaguang/DCRNN/tree/master/data/sensor_graph) (tensorflow version). There is a complete data information.

**Comment by Daishijun** [comment]
> Maybe you can refer the [DCRNN](https://github.com/liyaguang/DCRNN/tree/master/data/sensor_graph) (tensorflow version). There is a complete data information.

Thank you
