### ISSUE TITLE
Hi! Great work! I have a question about the code. Have you mentioned adj_mx.pkl? There is no such file.

### ISSUE THREAD

**Issue by DLwbm123** [nnzhan/Graph-WaveNet#2]

**Comment by zhanchey** [comment]
the same problem

**Comment by gcorso** [comment]
You have to use the scripts in the DCRNN model that you can find [here](https://github.com/liyaguang/DCRNN). In particular, for that you will need the gen_adj_mx.py.

**Comment by nnzhan** [comment]
Thanks for point it out. Sorry I forget to mention that adj_mx.pkl file we used is the same as provided in the data folder of DCRNN.
