### ISSUE TITLE
实验结果：为什么table2里的结果要比table3里的低很多？

### ISSUE THREAD

**Issue by yufann** [nnzhan/Graph-WaveNet#21]
为什么table2里的结果要比table3里的低很多，我的疑问是：table3在做消融实验，table3中加粗的最好的结果不应该放在table2 里面吗？为什么现在不是这样的呢？请各位大神看到后相助 ，十分感谢

**Comment by Factos001** [comment]
The author said Table 3 is the average score of MAE, RMSE, and MAPE over 12 prediction horizons, so, make sense.

**Comment by yufann** [comment]
> The author said Table 3 is the average score of MAE, RMSE, and MAPE over 12 prediction horizons, so, make sense.

ok thanks!
