### ISSUE TITLE
关于数据的输入问题

### ISSUE THREAD

**Issue by packer-c** [nnzhan/Graph-WaveNet#35]
感谢文章和代码！

请问一下，如果预测60分钟的交通流，数据首先输入t1-t12的，然后预测t13-t24时刻的交通流（即预测一个小时）；然后第二步是的输入是t25-t36，然后预测t37-t48吗？以此类推，请问我这样理解的对吗？

**Comment by Eversee22** [comment]
不对。它这个数据处理是按照固定窗口（如24）来的，按照步幅1滑动。比如hisroty是t1-t12,future是t13-t24, 下一个数据就是t2-t13,和t14-t25，依此类推

**Comment by packer-c** [comment]
感谢解答！
